packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@sentry/cli': true
  esbuild: false
  protobufjs: false
  sharp: false
  workerd: false

autoInstallPeers: true
linkWorkspacePackages: true
shamefullyHoist: true
sharedWorkspaceShrinkwrap: true
access: public
enablePrePostScripts: true
legacyPeerDeps: true
nodeLinker: hoisted
saveExact: true
