// GENERATED by scripts/generate-expected-schema.mjs - do not edit.
// Regenerate with: pnpm --filter @onlooker/db generate:expected-schema
export const EXPECTED_SCHEMA = {
	lesson_feed: {
		columns: [
			{
				name: "seq",
				type: "INTEGER",
				notnull: 1,
				pk: 0,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "lesson_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "kind",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			{
				name: "lesson_feed_lesson_id_idx",
				unique: false,
				columns: ["lesson_id"],
			},
			{
				name: "lesson_feed_user_seq_idx",
				unique: true,
				columns: ["user_id", "seq"],
			},
		],
	},
	lessons: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "visibility",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "status",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "schema_version",
				type: "INTEGER",
				notnull: 1,
				pk: 0,
			},
			{
				name: "body",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "promoted_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "updated_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			{
				name: "lessons_user_id_idx",
				unique: false,
				columns: ["user_id"],
			},
			{
				name: "lessons_user_promoted_at_idx",
				unique: false,
				columns: ["user_id", "promoted_at", "id"],
			},
		],
	},
	machine_tokens: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "name",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "token_hash",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "last_used_at",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "revoked_at",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "inventory",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "inventory_at",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
		],
		indexes: [
			{
				name: "machine_tokens_token_hash_idx",
				unique: true,
				columns: ["token_hash"],
			},
			{
				name: "machine_tokens_user_id_idx",
				unique: false,
				columns: ["user_id"],
			},
		],
	},
	sessions: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "token_hash",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "expires_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			{
				name: "sessions_expires_at_idx",
				unique: false,
				columns: ["expires_at"],
			},
			{
				name: "sessions_token_hash_idx",
				unique: true,
				columns: ["token_hash"],
			},
			{
				name: "sessions_user_id_idx",
				unique: false,
				columns: ["user_id"],
			},
		],
	},
	users: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "email",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "password_hash",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "name",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "email_verified",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "updated_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			{
				name: "users_created_at_idx",
				unique: false,
				columns: ["created_at"],
			},
			{
				name: "users_email_idx",
				unique: true,
				columns: ["email"],
			},
		],
	},
	verification_tokens: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "token_hash",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "type",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "expires_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			{
				name: "verification_tokens_expires_at_idx",
				unique: false,
				columns: ["expires_at"],
			},
			{
				name: "verification_tokens_token_idx",
				unique: true,
				columns: ["token_hash"],
			},
			{
				name: "verification_tokens_type_idx",
				unique: false,
				columns: ["type"],
			},
			{
				name: "verification_tokens_user_id_idx",
				unique: false,
				columns: ["user_id"],
			},
		],
	},
} as const;
