// GENERATED by scripts/generate-expected-schema.mjs - do not edit.
// Regenerate with: pnpm --filter @onlooker/db generate:expected-schema
export const EXPECTED_SCHEMA = {
	sessions: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "token_hash",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "expires_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			"sessions_expires_at_idx",
			"sessions_token_hash_idx",
			"sessions_user_id_idx",
		],
	},
	users: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "email",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "password_hash",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "name",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "email_verified",
				type: "TEXT",
				notnull: 0,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "updated_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: ["users_created_at_idx", "users_email_idx"],
	},
	verification_tokens: {
		columns: [
			{
				name: "id",
				type: "TEXT",
				notnull: 1,
				pk: 1,
			},
			{
				name: "user_id",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "token",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "type",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "expires_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
			{
				name: "created_at",
				type: "TEXT",
				notnull: 1,
				pk: 0,
			},
		],
		indexes: [
			"verification_tokens_expires_at_idx",
			"verification_tokens_token_idx",
			"verification_tokens_type_idx",
			"verification_tokens_user_id_idx",
		],
	},
} as const;
