/**
 * Every icon in `icons/`, as a value and a type.
 *
 * A union rather than `string` so `<Icon name="Lightbolb" />` fails at compile
 * time instead of 404ing in front of a user. Kept honest by a test in
 * assets.test.ts that compares this list against the directory - without it,
 * adding a PNG and forgetting this file produces a name nobody can use, and
 * renaming one produces a type that lies.
 *
 * Type-only consumers get erased at build, so this file needs no bundling.
 */
export const ICON_NAMES = [
	"Backpack",
	"Basket",
	"Battery",
	"Book",
	"Bottle",
	"Briefcase",
	"CD",
	"Car",
	"Cash",
	"Cash2",
	"CatHead",
	"CatchingNet",
	"ChestTreasure",
	"Chili",
	"Cloud",
	"Coin",
	"Coin2",
	"CookingPot",
	"Cutlery",
	"Document",
	"Download",
	"Enter",
	"Enter2",
	"Exit",
	"Eye",
	"FloppyDisk",
	"Flower",
	"Flower2",
	"FlowerPot",
	"Gamepad",
	"Gamepad2",
	"Gamepad3",
	"Gear",
	"Hammer",
	"Home",
	"Info",
	"Key",
	"Keyboard",
	"Letter",
	"Lightbulb",
	"Locked",
	"Luggage",
	"MagnifyingGlass",
	"Medicine",
	"Microphone",
	"Monitor",
	"MouseComputer",
	"MusicNotes",
	"Necklace",
	"Option",
	"PaintBrush",
	"Pencil",
	"PetBowl",
	"PetBrush",
	"Piano",
	"Play",
	"PlayPause",
	"Plug",
	"PotionRed",
	"Power",
	"Restart",
	"Scissors",
	"ShoppingCart",
	"Skull",
	"Sleep",
	"Spatula",
	"SpeakerMute",
	"SpeakerOn",
	"Sun",
	"Team",
	"Telephone",
	"Touch",
	"Trashbin",
	"Trophy",
	"Unlocked",
	"Upload",
	"Wheat",
	"Wrench",
	"Wrench2",
	"Wrench3",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
