#!/usr/bin/env node
// Writes the Homebrew formula for the CLI.
//
// Not goreleaser: that is Go-specific, and this CLI is a bundled JS file that
// runs on Homebrew's node. Usage:
//   node scripts/write-formula.mjs <version> <tarball-url> <sha256>

const [version, url, sha256] = process.argv.slice(2);
if (!version || !url || !sha256) {
	console.error("usage: write-formula.mjs <version> <url> <sha256>");
	process.exit(1);
}

process.stdout.write(`# typed: false
# frozen_string_literal: true

# Generated by scripts/write-formula.mjs. DO NOT EDIT.
class Onlooker < Formula
  desc "Push approved lessons from your machine to app.onlooker.dev"
  homepage "https://onlooker.dev"
  url "${url}"
  sha256 "${sha256}"
  version "${version}"
  license "BlueOak-1.0.0"

  depends_on "node"

  def install
    libexec.install "onlooker.mjs"
    (bin/"onlooker").write <<~SH
      #!/bin/bash
      exec "#{Formula["node"].opt_bin}/node" "#{libexec}/onlooker.mjs" "$@"
    SH
    chmod 0555, bin/"onlooker"
  end

  # No service block. This CLI has no daemon: it runs, syncs, and exits.
  # Anyone upgrading from the retired Go agent has a launchd job pointed at a
  # subcommand that no longer exists, and Homebrew cannot stop it for them.
  def caveats
    <<~EOS
      If you previously ran the Onlooker agent as a service, stop it:

        brew services stop onlooker

      This version has no daemon. Link once, then sync when you want to:

        onlooker link
        onlooker sync

      The retired agent buffered events at ~/.onlooker/buffer.db and kept its
      settings in ~/.onlooker/config.toml. Neither is read by this version.
      The buffer can be large - it grew unbounded whenever sending failed -
      and holds events this CLI does not send, so nothing here will deliver
      them. Delete it only if you no longer want them.
    EOS
  end

  test do
    assert_match "onlooker", shell_output("#{bin}/onlooker --help")
  end
end
`);
